name: Maven Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      # This step checks out the repository code

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17' # Specify the version of JDK required
        distribution: 'temurin' # Specify the JDK distribution

    - name: Build with Maven
      run: mvn clean install -X
      # Added verbose output for debugging

    - name: Run tests
      run: mvn test -X
      # Added verbose output for debugging

